//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model
{
    using RDTools.Common;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClientEntities : DbContext
    {
        public ClientEntities()
            : base("name=ClientEntities")
        {
    	   base.Database.Connection.ConnectionString = AppConfig.DataBaseConnectionString();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Operator> Operator { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Office> Office { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<OperatorMenuAuthority> OperatorMenuAuthority { get; set; }
    }
}
