//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.OperatorMenuAuthority = new HashSet<OperatorMenuAuthority>();
        }
    
        public string Nodeid { get; set; }
        public string NodeName { get; set; }
        public string ParentNode { get; set; }
        public string isEndNode { get; set; }
        public string Pluginid { get; set; }
        public string Commentary { get; set; }
        public string Disporder { get; set; }
        public int type { get; set; }
        public byte[] image { get; set; }
        public Nullable<bool> IsChoose { get; set; }
    
        public virtual ICollection<OperatorMenuAuthority> OperatorMenuAuthority { get; set; }
    }
}
