//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public string Roleid { get; set; }
        public string Role1 { get; set; }
        public string CodeNo { get; set; }
        public string SpellNo { get; set; }
        public string CustomNo { get; set; }
        public string StrokeNo { get; set; }
    }
}
