//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string Userid { get; set; }
        public string UserName { get; set; }
        public string CodeNo { get; set; }
        public string SpellNo { get; set; }
        public string CustomNo { get; set; }
        public string StrokeNo { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Nation { get; set; }
        public string Diploma { get; set; }
        public string Officeid { get; set; }
        public string VestDept { get; set; }
        public string Duty { get; set; }
        public string Role { get; set; }
        public string LaborageNo { get; set; }
        public Nullable<decimal> ExamineMoney { get; set; }
        public Nullable<int> RegisterLimitNo { get; set; }
        public Nullable<int> BespeakLimitNo { get; set; }
        public Nullable<decimal> PledgeMoney { get; set; }
        public string Workkind { get; set; }
        public int PrescriptionRight { get; set; }
        public string ExamineName { get; set; }
        public int StopFlag { get; set; }
        public string StopOperator { get; set; }
        public Nullable<System.DateTime> StopDate { get; set; }
        public string Remark { get; set; }
        public string TELEPHONE { get; set; }
    }
}
